from .base_error import BaseError


class InternalError(BaseError):
    pass